{% set name = "jupyterlab-autosave-on-focus-change" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_autosave_on_focus_change-{{ version }}.tar.gz
  sha256: 549de0256fbd3c02dd6e6454960e44e5cb710ee50378f13ad0fae74eaec8d94b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - pip
    - python >=3.8
  run:
    - jupyterlab >=4.0.0,<5
    - python >=3.8

test:
  imports:
    - jupyterlab_autosave_on_focus_change
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab_autosave_on_focus_change.*OK"
  requires:
    - pip

about:
  home: https://github.com/s-weigand/jupyterlab_autosave_on_focus_change
  summary: Jupyterlab extension to autosave files on focus change
  dev_url: https://github.com/s-weigand/jupyterlab_autosave_on_focus_change
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
