{% set name = "jupyterlab-autosave-on-focus-change" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_autosave_on_focus_change-{{ version }}.tar.gz
  sha256: 1b27ef83ac96e750d4050a82f347c9e5766e310a259ba683f7f74fca8b6ffc51

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.6
  run:
    - jupyter-packaging <2,~=0.9
    - jupyterlab ~=3.0
    - python >=3.6

test:
  imports:
    - jupyterlab_autosave_on_focus_change
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab_autosave_on_focus_change.*OK"
  requires:
    - pip

about:
  home: https://github.com/s-weigand/jupyterlab_autosave_on_focus_change
  summary: Jupyterlab extension to autosave files on focus change
  dev_url: https://github.com/s-weigand/jupyterlab_autosave_on_focus_change
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
